Token middleware
gtd-checklist/checklist-core pull request #4
Opened 2018-11-14 18:35 UTC by MikhailLoginov

2018-11-15 13:21 UTC, jarith requested changes

2018-11-15 13:21 UTC, jarith commented on src/middleware/validators.js
> +  if (typeof bearerHeader === 'undefined') {
Эквивалентно `!bearerHeader`

2018-11-15 13:21 UTC, jarith commented on config/index.js
> +const JWT_EXPIRE_TIME = 1800; // seconds
Думаю, у нас и так достаточно кофигов. Лучше вынести в .env + добавить в now.json

2018-11-15 13:21 UTC, jarith commented on index.js
> +app.use(errorHandler);
Бесполезная middleware. Смысл был в том, что `validateToken`, который стоит перед роутами, сам вернет 401 ошибку и выполнение даже не дойдет до роутов

2018-11-15 13:21 UTC, jarith commented on src/middleware/validators.js
> +      next(err);
Пропущен `return`

2018-11-15 13:21 UTC, Jarith commented on src/models/User.js
> +    const exp = Math.floor(Date.now()/1000) + JWT_EXPIRE_TIME;
Какой смысл переводить время в секунды? На фронте тогда тоже придется это делать. Проще сразу все в миллисекундах хранить

2018-11-15 13:21 UTC, Jarith commented on src/models/User.js
> +    return { token, exp };
Разве в токене не хранится информация о времени жизни? Кажется  `exp`  без надобности

2018-11-16 17:57 UTC, MikhailLoginov commented on src/models/User.js
> +    return { token, exp };
хранится, но только в зашифрованном виде. в то время как поле exp предназначено для фронтенда

2018-11-18 19:31 UTC, jarith requested changes

2018-11-18 19:31 UTC, Jarith commented on src/models/User.js
> +    return { token, exp };
@MikhailLoginov, честно говоря не проверял, что возвращает `jwt.sign`, но это по-идее должны быть Base64 от данных, разделенные точкой + подпись. Подробнее можно посмотреть на https://jwt.io/

2018-11-18 19:31 UTC, Jarith commented on src/routes/auth.js
> +  user.password = undefined;
Не очень понял, для чего это

2018-11-18 19:42 UTC, MikhailLoginov commented on src/routes/auth.js
> +  user.password = undefined;
Чтобы не отсылать обратно пароль

2018-11-18 19:45 UTC, MikhailLoginov commented on src/models/User.js
> +    return { token, exp };
ты хочешь их дешифровать на клиенте?

2018-11-23 18:17 UTC, merged